In [9]:
% matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

plt.rcParams["figure.figsize"] = (20.0, 10.0)
from mpl_toolkits.mplot3d import Axes3D

data:pd.DataFrame = pd.read_csv("d:/data/student.csv")
print(data.shape)
data.head()

(1000, 3)


<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Math</th>
      <th>Reading</th>
      <th>Writing</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>48</td>
      <td>68</td>
      <td>63</td>
    </tr>
    <tr>
      <th>1</th>
      <td>62</td>
      <td>81</td>
      <td>72</td>
    </tr>
    <tr>
      <th>2</th>
      <td>79</td>
      <td>80</td>
      <td>78</td>
    </tr>
    <tr>
      <th>3</th>
      <td>76</td>
      <td>83</td>
      <td>79</td>
    </tr>
    <tr>
      <th>4</th>
      <td>59</td>
      <td>64</td>
      <td>62</td>
    </tr>
  </tbody>
</table>
</div>

In [10]:
math: np.ndarray = data["Math"].values
read: np.ndarray = data["Reading"].values
write: np.ndarray = data["Writing"].values

#Ploting the scores as scatter plot
fig: plt.Figure = plt.figure()
ax: Axes3D = Axes3D(fig)
ax.scatter(math, read, write, color="#ef1234")
plt.show()

In [28]:
m: int = len(math)
x0: np.ndarray = np.ones(m)
X: np.ndarray = np.array([x0, math, read])[0:3].T
X[0:3]

array([[  1.,  48.,  68.],
       [  1.,  62.,  81.],
       [  1.,  79.,  80.]])

In [29]:
#Initial Coefficients
B: np.ndarray = np.array([0] * 3)
Y: np.ndarray = np.array(write)[0:3]
alpha: float = 0.0001
B

array([0, 0, 0])

In [15]:
def cost_function(X: np.ndarray, Y: np.ndarray, B: np.ndarray)-> float:
    m: int = len(Y)
    J: float = np.sum((X.dot(B) - Y) ** 2) / (2 * m)
    return J


2470.11


In [16]:
inital_cost:float = cost_function(X, Y, B)
print(inital_cost)

2470.11


In [27]:
X[0:5].dot(B)

array([ 0.,  0.,  0.,  0.,  0.])

Hypothesis: hβ(x)=βTx

Loss: (hβ(x)−y)

Gradient: (hβ(x)−y)xj

Gradient Descent Updation: βj:=βj−α(hβ(x)−y)xj)


In [23]:
from typing import *

def gradient_descent(X: np.ndarray,
                     Y: np.ndarray,
                     B: np.ndarray,
                     alpha: float,
                     iterations: int)-> (np.ndarray, List[float]):

    cost_history: List[float] = [0] * iterations
    m: int = len(Y)
    for iteration in range(iterations):
        # Hypothesis values
        h: np.ndarray = X.dot(B)
        # Difference b/w Hypothesis and Actual Y
        loss: np.ndarray = h - Y
        #Gradient calcutation
        gradient: float = X.T.dot(loss) / m
        #Changing values of B using Gradient
        B = B - alpha * gradient
        #New Cost Value
        cost: float = cost_function(X, Y, B)
        cost_history[iteration] = cost

    return B, cost_history


In [24]:
#100000 iterations
newB, cost_history = gradient_descent(X, Y, B, alpha, 100000)
#New values of B
print(newB)
#Final cost of new B
print(cost_history[-1])

[-0.47889172  0.09137252  0.90144884]
10.4751234735


In [26]:
def rmse(Y: np.ndarray, Y_pred: np.ndarray)-> float:
    rmse: float = np.sqrt(sum((Y - Y_pred) ** 2) / len(Y))
    return rmse

def r2_score(Y, Y_pred)-> float:
    mean_y: float = np.mean(Y)
    ss_tot: float = sum((Y - mean_y) ** 2)
    ss_res: float = sum((Y - Y_pred) ** 2)
    r2: float = 1 - (ss_res / ss_tot)
    return r2

Y_pred: np.ndarray = X.dot(newB)
print(rmse(Y, Y_pred))
print(r2_score(Y, Y_pred))


4.57714397273
0.909722327306
